# Generated by Django 5.0.7 on 2024-07-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject'),
        ),
    ]
