# Generated by Django 5.0.7 on 2024-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_subject_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='students.subject'),
        ),
    ]
