# Generated by Django 5.0.7 on 2024-07-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_customuser_password1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='hod',
        ),
    ]
