# Generated by Django 5.0.7 on 2024-07-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_profile_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, default='media\\profile_images\\default.jpeg', null=True, upload_to='profile_images/'),
        ),
    ]
