# Generated by Django 5.0.7 on 2024-07-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, default='/profile_images/default.jpeg', null=True, upload_to='profile_images/'),
        ),
    ]
