# Generated by Django 5.0.7 on 2024-07-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollno',
            new_name='roll_no',
        ),
    ]
