# Generated by Django 5.0.7 on 2024-07-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
