# Generated by Django 5.0.7 on 2024-07-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_classgroup_alter_subject_name_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classgroup'),
        ),
    ]
