# Generated by Django 5.0.7 on 2024-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_student_classgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.FileField(upload_to='', verbose_name='assignment_images/'),
        ),
    ]
