# Generated by Django 5.0.7 on 2024-08-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='classgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classgroup'),
        ),
    ]
