# Generated by Django 5.0.7 on 2024-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_test_classgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
