# Generated by Django 5.0.7 on 2024-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_test_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateTimeField(),
        ),
    ]
