# Generated by Django 5.0.7 on 2024-08-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_alter_test_test_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='year',
            field=models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classes'),
        ),
    ]
