# Generated by Django 5.0.7 on 2024-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_classes_alter_classgroup_year_alter_classgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
