# Generated by Django 5.0.7 on 2024-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_alter_feedback_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('book_type', models.CharField(max_length=100)),
            ],
        ),
    ]
