# Generated by Django 5.0.7 on 2024-08-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_type',
        ),
    ]
