# Generated by Django 5.0.7 on 2024-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_remove_books_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
