# Generated by Django 5.0.7 on 2024-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
