# Generated by Django 5.0.7 on 2024-08-10 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
