# Generated by Django 5.0.7 on 2024-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_alter_studentscore_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
