# Generated by Django 5.0.6 on 2024-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
