# Generated by Django 5.0.6 on 2024-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
