# Generated by Django 5.0.6 on 2024-08-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_studentanswer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='test',
        ),
    ]
