# Generated by Django 5.0.6 on 2024-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_timeslot_remove_timetable_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=9, null=True),
        ),
    ]
