# Generated by Django 5.1.1 on 2024-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_remove_timeslot_day_of_week_timetable_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passing_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
