# Generated by Django 5.1.1 on 2024-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_test_passing_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='is_passed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
