# Generated by Django 5.2 on 2025-05-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0067_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, default='profile_images/default.jpeg', null=True, upload_to='profile_images/'),
        ),
    ]
