# Generated by Django 5.2 on 2025-05-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0068_alter_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
