services:
  db:
    image: mysql:5.7
    container_name: attendance
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance
    ports:
      - "8000:8000"
