# Generated by Django 5.0.6 on 2024-08-15 09:29

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_auto_20230814_1234'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='studentanswer',
        #     name='test',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Test'),
        # ),
    ]
